### ISSUE TITLE
Why cuda stream?

### ISSUE THREAD

**Issue by hadoopmore** [quiver-team/torch-quiver#101]
你好，我对于您如何在 UVA 模式下进行 GPU 采样的方法很感兴趣，所以进到 C++代码进行了简单的阅读。但是我另外发现了一个有点奇怪的现象，我注意到你们在采样的时候用到了 CUDA Stream，也就是说你们实际模型计算是在默认CUDA 流，但是在 GPU采样时用的是非默认CUDA流。我对这个做法有点疑惑，因为在我们实际进行模型 forward 计算的时候，必须等到GPU采样的结果返回了才可以开始计算，也就是说这里其实并不存在一个可以异步执行的步骤，而必须是同步执行。请问有人可以解答一下吗？这样做会带来速度提升之类的吗？

**Comment by ZenoTan** [comment]
We use our own cuda stream in sampling, but changing it to the default stream will not have any negative effects. The model forward and the sampling can not be parallelized to improve throughput.

**Comment by hadoopmore** [comment]
Thank you!
