### ISSUE TITLE
Cuda Error, When run the quiver example with the dataset of ogbn-papers100M in the benchmark 

### ISSUE THREAD

**Issue by SoupFree** [quiver-team/torch-quiver#102]
您好，我发现了一个bug，当执行的benchmark ogbn-papers100M的示例程序的时候出现了Cuda Error（`CUBLAS_STATUS_NOT_INITIALIZED `），当然我已经根据文档中提示已经执行了
<img width="1008" alt="图片" src="https://user-images.githubusercontent.com/95961813/145672869-8fc0339f-7d94-4e96-a6a9-fde8d40a70c9.png">

我通过Debug发现了具体具体出错的地方，当执行cudaHostRegister时候会返回cuda error，但是没有进行拦截，返回错误code是1，我查了一下具体错误是 `cudaErrorInvalidValue`
<img width="635" alt="图片" src="https://user-images.githubusercontent.com/95961813/145672906-df2f20fb-b0e8-4f26-8f04-3a2b91fcff82.png">

通过日志分析发现，当cudaHostRegister一旦操作进行了30000000000 Bytes HostMapped的时候就会出错，比较奇怪。
<img width="471" alt="图片" src="https://user-images.githubusercontent.com/95961813/145672996-6fae59b6-11f4-474a-8f2b-d7673adbaa83.png">

辛苦开发者帮忙看看这个问题，谢谢！

**Comment by eedalong** [comment]
看起来是memory不够用了，你要不试一下把 shm 调的更大一些看看

**Comment by SoupFree** [comment]
<img width="650" alt="图片" src="https://user-images.githubusercontent.com/95961813/145673381-d0419493-5577-4519-ae46-19e49e8cf8c1.png">
我们的memory是够用的，同时把shm的memory设置到了256G还是出错

**Comment by ZenoTan** [comment]
你可以试试这种方法能不能行
https://stackoverflow.com/questions/58804022/how-to-resize-dev-shm

**Comment by wawltor** [comment]
> > 你可以试试这种方法能不能行 https://stackoverflow.com/questions/58804022/how-to-resize-dev-shm
> 
> @SoupFree 使用这种方式之后问题解决了么～

嗯嗯 解决了 谢谢！

**Comment by eedalong** [comment]
好的～
