### ISSUE TITLE
CUDA

### ISSUE THREAD

**Issue by xiongyt-bear** [quiver-team/torch-quiver#104]
Excuse me, I am confused by your CSRSample kernel. The block size is 128, but the title size is 64, actually half of threads in a block are not used. Can you explain about it to me?

**Comment by ZenoTan** [comment]
Actually the tile size is the number of rows for each block. You can reference [DGL's GPU sampling](https://github.com/dmlc/dgl/blob/master/src/array/cuda/rowwise_sampling.cu).

**Comment by xiongyt-bear** [comment]
okay， thank you very much




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "quiver-team/torch-quiver"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月3日(星期一) 凌晨1:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [quiver-team/torch-quiver] CUDA (Issue #104)





 
Actually the tile size is the number of rows for each block. You can reference DGL's GPU sampling.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
