### ISSUE TITLE
Use memory pool for memory allocation when sampling && feature collecting

### ISSUE THREAD

**Issue by eedalong** [quiver-team/torch-quiver#115]

**Comment by eedalong** [comment]
We create a tensor through pytorch pytorch already use `CudaCachingAllocator` for memory allocation on device.
I also implemented [a simple test](https://github.com/quiver-team/torch-quiver/blob/feature/shardtensor_write/srcs/cpp/src/quiver/cuda/quiver_feature.cu#L446
) to check tensor's memory allocator and it shows that a cuda tensor indeed uses `cudaCachingAllocator` for memory allocation.

**Comment by lgarithm** [comment]
What about the performance of `cudaCachingAllocator`?

**Comment by eedalong** [comment]
We did some experiments on `cudaCachingAllocator` and it shows great performance. So we will close this issue.
