### ISSUE TITLE
AttributeError: module 'torch_quiver' has no attribute 'device_quiver_from_csr_array'

### ISSUE THREAD

**Issue by LukeLIN-web** [quiver-team/torch-quiver#133]
I install torch-quiver           0.1.0 from https://github.com/quiver-team/torch-quiver/blob/main/docker/README.md
when i run examples/pyg/reddit_quiver.py,
it shows AttributeError: module 'torch_quiver' has no attribute 'device_quiver_from_csr_array'

**Comment by LukeLIN-web** [comment]
I tried uninstall and install 0.1.1. 
It will hang at: 
https://github.com/quiver-team/torch-quiver/blob/0592669225954e46d9c57c0ca121c365af47b57f/examples/pyg/reddit_quiver.py#L29

**Comment by ZenoTan** [comment]
Thanks for the ticket! https://github.com/quiver-team/torch-quiver/blob/main/srcs/cpp/src/quiver/cuda/quiver_sample.cu#L361-L461 The function calls this C++ function internally, and in your case it is hanging somewhere the middle.

**Comment by LukeLIN-web** [comment]
> Thanks for the ticket! https://github.com/quiver-team/torch-quiver/blob/main/srcs/cpp/src/quiver/cuda/quiver_sample.cu#L361-L461 The function calls this C++ function internally, and in your case it is hanging somewhere the middle.

May you know how can i sort it out?
Can I find any docker images that can run examples?  I pull docker pull zenotan/torch_quiver:test. But it failed

**Comment by LukeLIN-web** [comment]
I figure it out, because I use a A100 GPU. compiled codes cannot run at A100. I change to V100 and run successfully.
