### ISSUE TITLE
Benchmark mag240m, preprocessing issues

### ISSUE THREAD

**Issue by Juelin-Liu** [quiver-team/torch-quiver#157]
I installed torch-quiver within a Conda environment:

- Python=3.10
- Torch=2.0.0
- Cuda=11.8
- Torch-Quiver=0.1.1 (installed via pip)

I can use Quiver for feature extraction and uva sampling. I want to run benchmark on mag240m. Yet, I cannot run `benchmark/ogbn-mag240m/preprocess.py` because two functions are missing:

- partition_without_replication
- select_nodes

The corresponding errors are:

- ImportError: cannot import name 'partition_without_replication' from 'quiver.partition'
- ImportError: cannot import name 'select_nodes' from 'quiver.partition'

Would you mind let me know how I can find the code for those functions? Thanks!

**Comment by luomai** [comment]
Thanks for the question. We have confirmed the issue is caused by the pre-processing script not using the updated partitioning APIs. @ZenoTan and @CongjieHe are going to create a PR to fix this.
