### ISSUE TITLE
The strategy of hot/cold feature allocation in the different device

### ISSUE THREAD

**Issue by hadoopmore** [quiver-team/torch-quiver#84]
在特征抽取的过程中，可以将特征划分为Hot 和 Cold data，请问具体的划分策略是什么了？

**Comment by ZenoTan** [comment]
我们现在的策略是通过排序节点的度 (sorted node degree) 来判断节点的特征是不是被高频访问，我们优先在GPU上放易被访问的特征。我们之后会有更优化的策略来完成这个划分。

**Comment by hadoopmore** [comment]
请问下具体代码在哪里呢，想学习一下。

**Comment by eedalong** [comment]
@hadoopmore [在这里～](https://github.com/quiver-team/torch-quiver/blob/main/srcs/python/quiver/feature.py#L114)

**Comment by eedalong** [comment]
We will leave this issue unclosed for a while so that people having the same question can also benefit from this discussion

**Comment by Ningsir** [comment]
请问你们提取特征的时候是怎么判断节点的特征是热数据还是冷数据呢

**Comment by Ningsir** [comment]
我明白了，你们在处理冷数据和热数据的时候，打乱了特征的顺序，并且使用feature_order记录节点ID和对应特征索引的映射关系，在提取特征的时候使用的是新的索引值。

**Comment by eedalong** [comment]
@Ningsir correct
