### ISSUE TITLE
Performance evaluation about dgl, pyg and torch-quiver

### ISSUE THREAD

**Issue by Ningsir** [quiver-team/torch-quiver#86]
# Experiment settings
The experiment settings are as follows: 
* Ubuntu 18.04, P100 GPU, 16G GPU memory;
* dataset: ogbn;
* dgl: 0.7.1
* pyg: 2.0.2
* torch-quiver: 0.1.0
* hiddens = 256，neighbors = [15, 10, 5]，epochs = 10, batch_size = 1024.

code: [pyg](https://github.com/quiver-team/torch-quiver/blob/main/examples/pyg/ogbn_products_sage_pyg.py), [quiver](https://github.com/quiver-team/torch-quiver/blob/main/examples/pyg/ogbn_products_sage_quiver.py), [dgl](https://github.com/dmlc/dgl/blob/master/examples/pytorch/graphsage/train_sampling.py)
# Result
metrics: average epoch time.

**num_workers = 4**

* dgl: 13.60 S
* pyg: 30.07 S

**num_workers = 8:**

* dgl: 9.78 S
* pyg:  17.61 S

**num_workers = 12:**
* dgl: 8.92 S
* pyg: 13.42 S

**sample on GPU:**
* quiver: 11.04 S
* dgl: 3.64 S

# Question
1. PyG’s data load is much slower than DGL’s. Can you improve the speed of data load?
1. Why is the sampling speed of PyG so much slower than DGL?

**Comment by eedalong** [comment]
1. Profiling result in `num_workers = 8`, `num_workers = 4`, `num_workers = 12` settings, you are using original `pyg` or you integrated `quiver` in your code
2. About `Sample on GPU` , you are using dgl's CPU sampler or GPU sampler? quiver's sampler supports `UVA` mode and `GPU` mode, If you are using  dgl's GPU sampler, you can also enable `GPU` mode in quiver.sampler

**Comment by Ningsir** [comment]
1. using original pyg;
2. I will try GPU mode.

**Comment by eedalong** [comment]
"""
PyG’s data load is much slower than DGL’s. Can you improve the speed of data load?
"""
Original PyG's dataloader's performance is indeed a problem,  We will try to discuss with PyG's team and see what we can do.

**Comment by eedalong** [comment]
> 1. using original pyg;
> 2. I will try GPU mode.

Great, you can set `mode='GPU'` in your `quiver.pyg.GraphSageSampler`

**Comment by Ningsir** [comment]
> > 1. using original pyg;
> > 2. I will try GPU mode.
> 
> Great, you can set `mode='GPU'` in your `quiver.pyg.GraphSageSampler`

I try it, but the performance improvement is not obvious. Average epoch time is 10.32 S compared to 11.04 S.

**Comment by eedalong** [comment]
> > > 1. using original pyg;
> > > 2. I will try GPU mode.
> > 
> > 
> > Great, you can set `mode='GPU'` in your `quiver.pyg.GraphSageSampler`
> 
> I try it, but the performance improvement is not obvious. Average epoch time is 10.32 S compared to 11.04 S.

This means `sample` is no longer the key bottleneck, what's your device_cache_size in your `quiver.Feature`?

**Comment by Ningsir** [comment]
200MB @eedalong

**Comment by Ningsir** [comment]
In fact, I want to know the differences between DGL's sampling and PyG's sampling.

**Comment by Ningsir** [comment]
I would appreciate it if you could answer.

**Comment by eedalong** [comment]
Oh,  I see, I didnt notice you also post code here. 
1. You are profiling DGL with all feature data on GPU and sample with GPU, for fair comparison, you should also enable `GPU mode `in quiver's sampler and also set your `device_cache_size large` enough so that quiver caches more data on GPU for better throughput

> In fact, I want to know the differences between DGL's sampling and PyG's sampling.

DGL uses multi-thread sampling and pyg use single-thread sampling

**Comment by Ningsir** [comment]
num_workers is not the number of thread? 
```python
train_loader = NeighborSampler(data.edge_index, node_idx=train_idx,
                               sizes=[15, 10, 5], batch_size=1024,
                               shuffle=True, num_workers=12, persistent_workers=True)
```

**Comment by eedalong** [comment]
num_worker is the number of `process`

**Comment by eedalong** [comment]
DGL use openMP in sampler, [see this pr](https://github.com/dmlc/dgl/pull/3274/files)

**Comment by Ningsir** [comment]
I see. DGL's sampling is multi-process and multi-thread for each process, but PyG's sampling is multi-process and single-thread?

**Comment by eedalong** [comment]
> I see. DGL's sampling is multi-process and multi-thread for each process, but PyG's sampling is multi-process and single-thread?

correct

**Comment by Ningsir** [comment]
> DGL use openMP in sampler, [see this pr](https://github.com/dmlc/dgl/pull/3274/files)

Thank you very much.

**Comment by eedalong** [comment]
~
