### ISSUE TITLE
Error when cache size is larger than the size of feature

### ISSUE THREAD

**Issue by Joeyzhouqihui** [quiver-team/torch-quiver#97]
When I try to put all features in gpu memory, an error occur in the function "\_\_getitem\_\_" in file "feature.py".

I guess the root cause is in the function "append" in file "quiver_feature.cu" at line 193, which is "quiverRegister(tensor.data_ptr<float>(), data_size, cudaHostRegisterMapped);". 

The error will occur when trying to register zero-copy memory of 0 byte. The problem can be fixed by adding an if statement before registering memory to prevent memory registering when the feature tensor is empty.

**Comment by eedalong** [comment]
Hi, can you give us a minimal code example? quiver.Feature should have no problem with caching all data on GPU

**Comment by eedalong** [comment]
@Joeyzhouqihui

**Comment by Joeyzhouqihui** [comment]
Just run the example code "dist_sampling_ogb_reddit_quiver.py" and set the cache_size of feature to be larger than the size of reddit(537M).

**Comment by eedalong** [comment]
@Joeyzhouqihui yes, I reproduced this problem, seems there are some problems with quiver.Feature's IPC

**Comment by eedalong** [comment]
Hi, this is fixed in #98, please pull the latest code and try again~

**Comment by eedalong** [comment]
@Joeyzhouqihui
